### ISSUE TITLE
How to detect real devices like an ESP32?

### ISSUE THREAD

**Issue by yuriboeira11tx** [alexa-samples/skill-sample-python-smarthome-switch#6]
I've been trying for days to implement a Smart Home Skill with my own IoT device, but I don't just want to configure a device, but I want to set up a skill that is able to register any device and be able to control it with custom functions like rainbow mode from an LED strip.

**Comment by aszk** [comment]
This sample is for virtual switch. In general, you need to control these operations on device cloud or device side. Once your skill receive Alexa's response, you can simply use it as a trigger to operate your device. You should be able to find the device because you should have an account linking to your device cloud.
